FROM ruby:2.7
LABEL maintainer=ianbuena081191@gmail.com

ARG USER_ID
ARG GROUP_ID

RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user

ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

# Setup some dependencies (git for bundler, nokogiri and mysql bits)
RUN apt-get update -qq && \
  apt-get install -y build-essential git libxml2-dev libxslt1-dev \
  default-libmysqlclient-dev cmake pkg-config

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV BUNDLE_JOBS=4 \
  BUNDLE_RETRY=5 \
  BUNDLE_PATH=/bundle \
  BUNDLE_BIN=/bundle/bin \
  GEM_HOME=/bundle

ENV PATH="${BUNDLE_BIN}:${PATH}"

RUN gem install bundler

WORKDIR /opt/app
